In [1]:
from load_data import *

In [5]:
args= {'seed': 123, 'n_train': 700, 'derivative': True}

In [6]:
res = load_helens("../../data/helens", 0.5, **args)

In [7]:
res

(<torch.utils.data.dataset.Subset at 0x22f0d664fc8>,
 2)

In [9]:
for item in res[1]:
    print(item)

(tensor([0.1000, 0.0427]), tensor([ 3.7536e-01,  5.3329e-04, -3.0831e-04]))
(tensor([0.1500, 0.2564]), tensor([ 5.7359e-01, -4.0984e-05,  2.0976e-03]))
(tensor([0.0667, 0.1709]), tensor([ 4.0946e-01, -4.7495e-04,  1.8311e-04]))
(tensor([0.4333, 0.3248]), tensor([0.7823, 0.0011, 0.0015]))
(tensor([0.1667, 0.1282]), tensor([4.3560e-01, 3.4381e-04, 4.0052e-04]))
(tensor([0.1000, 0.4872]), tensor([5.4246e-01, 9.0209e-04, 2.9285e-04]))
(tensor([0.3500, 0.1709]), tensor([5.2228e-01, 4.6842e-04, 1.6121e-03]))
(tensor([0.3667, 0.1624]), tensor([5.2037e-01, 1.2445e-03, 3.0956e-04]))
(tensor([0.1833, 0.1197]), tensor([4.3127e-01, 2.4943e-04, 3.6225e-04]))
(tensor([0.3250, 0.2479]), tensor([5.7055e-01, 9.5040e-04, 4.6437e-04]))
(tensor([0.3083, 0.2821]), tensor([5.9816e-01, 7.0553e-04, 5.3750e-04]))
(tensor([0.3417, 0.2479]), tensor([0.5795, 0.0017, 0.0007]))
(tensor([0.1083, 0.4017]), tensor([5.2632e-01, 2.3858e-04, 9.1012e-04]))
(tensor([0.3167, 0.3162]), tensor([0.6399, 0.0014, 0.0009]))
(tens

(tensor([0.0083, 0.1282]), tensor([3.8632e-01, 1.4747e-04, 4.4468e-04]))
(tensor([0.3000, 0.2821]), tensor([5.9203e-01, 4.8500e-04, 1.1241e-03]))
(tensor([0.1000, 0.2479]), tensor([0.4602, 0.0014, 0.0009]))
(tensor([0.1167, 0.0940]), tensor([3.8947e-01, 8.2054e-04, 1.6131e-04]))
(tensor([0.4917, 0.3504]), tensor([8.5461e-01, 1.9226e-03, 3.2785e-04]))
(tensor([0.3750, 0.3761]), tensor([8.0948e-01, 1.6962e-03, 5.1761e-04]))
(tensor([0.2250, 0.3761]), tensor([5.9512e-01, 8.1906e-04, 5.5254e-04]))
(tensor([0.0083, 0.3419]), tensor([4.5922e-01, 2.1282e-04, 2.8862e-04]))
(tensor([0.3833, 0.2222]), tensor([5.8763e-01, 9.7142e-04, 5.1307e-04]))
(tensor([0.0333, 0.4444]), tensor([4.9658e-01, 3.2735e-04, 1.5557e-04]))
(tensor([0.3167, 0.4444]), tensor([7.8099e-01, 1.6438e-03, 6.3514e-04]))
(tensor([0.0083, 0.0342]), tensor([ 3.6574e-01,  4.5182e-04, -7.9528e-05]))
(tensor([0.1667, 0.4274]), tensor([0.5764, 0.0018, 0.0010]))
(tensor([0.0167, 0.4786]), tensor([0.4858, 0.0013, 0.0024]))
(tensor([0.

(tensor([0.4500, 0.1368]), tensor([5.5139e-01, 3.9897e-04, 6.2479e-04]))
(tensor([0.2833, 0.1538]), tensor([4.7773e-01, 2.2915e-04, 7.3474e-04]))
(tensor([0.4500, 0.1709]), tensor([ 0.5752, -0.0007,  0.0015]))
(tensor([0.0750, 0.3162]), tensor([0.4800, 0.0006, 0.0009]))
(tensor([0.0750, 0.4017]), tensor([ 0.5086,  0.0010, -0.0006]))
(tensor([0.2083, 0.1880]), tensor([4.8349e-01, 2.0781e-04, 3.2573e-04]))
(tensor([0.2833, 0.0855]), tensor([4.4199e-01, 2.9690e-04, 6.6604e-04]))
(tensor([0.2167, 0.2479]), tensor([5.4892e-01, 6.1826e-06, 2.0671e-05]))
(tensor([0.3333, 0.0427]), tensor([4.2789e-01, 8.8644e-05, 5.1924e-04]))
(tensor([0.2000, 0.1880]), tensor([4.8153e-01, 1.9780e-04, 2.6113e-04]))
(tensor([0.3333, 0.0769]), tensor([4.4315e-01, 2.4194e-04, 4.6330e-04]))
(tensor([0.4000, 0.2137]), tensor([5.9110e-01, 2.7403e-04, 1.4338e-03]))
(tensor([0.1083, 0.0427]), tensor([ 0.3815,  0.0010, -0.0030]))
(tensor([0.4750, 0.4701]), tensor([ 8.4509e-01, -6.2058e-04, -1.2150e-03]))
(tensor([0.250

(tensor([0.2167, 0.2308]), tensor([ 5.4416e-01, -5.2377e-04,  3.6471e-03]))
(tensor([0.0667, 0.1453]), tensor([3.9739e-01, 1.1412e-04, 6.7931e-04]))
(tensor([0.1250, 0.3675]), tensor([5.4061e-01, 3.5642e-04, 3.5784e-04]))
(tensor([0.4500, 0.4359]), tensor([0.9993, 0.0014, 0.0025]))
(tensor([0.3250, 0.3932]), tensor([0.7219, 0.0008, 0.0014]))
(tensor([0.3167, 0.1880]), tensor([ 0.5189, -0.0008,  0.0019]))
(tensor([0.3917, 0.2393]), tensor([0.6103, 0.0011, 0.0012]))
(tensor([0.2083, 0.0684]), tensor([4.1852e-01, 4.0778e-04, 1.3445e-04]))
(tensor([0.0667, 0.1624]), tensor([4.0531e-01, 6.2864e-05, 5.7746e-04]))
(tensor([0.4083, 0.1795]), tensor([5.4456e-01, 3.8212e-04, 1.0664e-03]))
(tensor([0.2250, 0.0256]), tensor([4.0206e-01, 3.6379e-04, 2.6259e-04]))
(tensor([0.3167, 0.3333]), tensor([6.5822e-01, 3.4553e-04, 3.7349e-03]))
(tensor([0.0833, 0.0855]), tensor([ 3.7964e-01, -6.6434e-05,  3.6886e-04]))
(tensor([0.0750, 0.4701]), tensor([ 5.2999e-01,  5.9238e-04, -1.0768e-05]))
(tensor([0.366

(tensor([0.4417, 0.3419]), tensor([0.8173, 0.0012, 0.0021]))
(tensor([0.4583, 0.2051]), tensor([0.6104, 0.0012, 0.0016]))
(tensor([0.3167, 0.1368]), tensor([ 4.7561e-01, -1.8702e-04,  1.2061e-03]))
(tensor([0.3583, 0.0256]), tensor([4.1357e-01, 3.1016e-04, 4.5659e-04]))
(tensor([0.2500, 0.2393]), tensor([5.4506e-01, 2.0005e-04, 6.1205e-04]))
(tensor([0.3500, 0.0085]), tensor([4.0407e-01, 1.7540e-04, 2.0313e-04]))
(tensor([0.1583, 0.2735]), tensor([ 0.5592,  0.0006, -0.0049]))
(tensor([0.0083, 0.0513]), tensor([ 3.6163e-01, -8.6999e-05,  1.7277e-04]))
(tensor([0.1667, 0.0940]), tensor([ 4.1333e-01, -2.0234e-04,  1.1176e-03]))
(tensor([0.0750, 0.2479]), tensor([ 0.4540, -0.0012,  0.0027]))
(tensor([0.5000, 0.0427]), tensor([ 0.4712, -0.0009,  0.0006]))
(tensor([0.4750, 0.1026]), tensor([4.9874e-01, 4.4218e-04, 4.8964e-04]))
(tensor([0.4083, 0.1709]), tensor([ 5.3604e-01, -1.4625e-06,  1.2644e-03]))
(tensor([0.0083, 0.2564]), tensor([4.3063e-01, 1.9205e-04, 5.8409e-04]))
(tensor([0.2667, 

(tensor([0.1417, 0.2137]), tensor([ 0.5685, -0.0021,  0.0009]))
(tensor([0.3250, 0.0427]), tensor([4.2667e-01, 1.7600e-04, 5.9551e-04]))
(tensor([0.4667, 0.1624]), tensor([5.6541e-01, 7.6836e-04, 4.2485e-04]))
(tensor([0.3583, 0.1111]), tensor([4.7138e-01, 3.1556e-04, 5.7862e-04]))
(tensor([0.5000, 0.2650]), tensor([ 0.7264, -0.0021,  0.0019]))
(tensor([0.2250, 0.3333]), tensor([0.5678, 0.0014, 0.0009]))
(tensor([0.0500, 0.0256]), tensor([3.7661e-01, 1.8721e-04, 8.6465e-05]))
(tensor([0.4250, 0.0684]), tensor([ 4.5530e-01, -3.8869e-04,  1.4961e-03]))
(tensor([0.2250, 0.2479]), tensor([5.4913e-01, 2.7541e-04, 1.8484e-04]))
(tensor([0.3833, 0.2051]), tensor([5.7297e-01, 1.0799e-04, 1.6631e-03]))
(tensor([0.1000, 0.3761]), tensor([5.1889e-01, 1.2821e-03, 1.1002e-04]))
(tensor([0.2667, 0.4359]), tensor([ 0.7071,  0.0013, -0.0009]))
(tensor([0.4583, 0.0513]), tensor([4.5527e-01, 3.8509e-04, 2.8387e-04]))
(tensor([0.3083, 0.0684]), tensor([4.4041e-01, 4.5224e-04, 4.4025e-04]))
(tensor([0.283

(tensor([0.1250, 0.0598]), tensor([ 3.8418e-01,  4.3826e-04, -4.4719e-05]))
(tensor([0.4750, 0.0085]), tensor([ 0.4161, -0.0006,  0.0009]))
(tensor([0.0417, 0.0769]), tensor([3.7056e-01, 1.1634e-04, 3.1194e-04]))
(tensor([0.4667, 0.2393]), tensor([0.6819, 0.0013, 0.0012]))
(tensor([0.3083, 0.1966]), tensor([5.2617e-01, 1.9933e-04, 8.2044e-04]))
(tensor([0.0500, 0.0513]), tensor([ 3.6680e-01,  1.6509e-04, -1.5567e-04]))
(tensor([0.1667, 0.0684]), tensor([0.4024, 0.0008, 0.0013]))
(tensor([0.3917, 0.1624]), tensor([5.2516e-01, 2.1983e-04, 1.4147e-03]))
(tensor([0.1417, 0.1111]), tensor([0.4104, 0.0007, 0.0008]))
(tensor([0.2000, 0.2735]), tensor([ 5.4878e-01, -5.5386e-04, -3.1165e-04]))
(tensor([0.0833, 0.1026]), tensor([3.8379e-01, 7.3044e-05, 2.4937e-04]))
(tensor([0.3000, 0.1709]), tensor([4.9503e-01, 3.1655e-04, 1.1672e-03]))
(tensor([0.4333, 0.1966]), tensor([5.7422e-01, 1.1073e-03, 4.9793e-04]))
(tensor([0.2750, 0.0513]), tensor([4.2560e-01, 2.0996e-04, 2.8566e-04]))
(tensor([0.125

(tensor([0.1333, 0.1197]), tensor([ 4.1116e-01, -1.6210e-04,  1.2846e-03]))
(tensor([0.3583, 0.2308]), tensor([ 5.7398e-01, -5.3226e-04,  1.7178e-03]))
(tensor([0.0333, 0.4701]), tensor([ 4.9714e-01,  3.2245e-04, -5.3332e-05]))
(tensor([0.4000, 0.4359]), tensor([0.9354, 0.0019, 0.0019]))
(tensor([0.4250, 0.4359]), tensor([0.9558, 0.0015, 0.0017]))
(tensor([0.2583, 0.1538]), tensor([0.4700, 0.0005, 0.0011]))
(tensor([0.0083, 0.4615]), tensor([ 4.8912e-01,  3.5370e-04, -7.1295e-04]))
(tensor([0.2750, 0.2051]), tensor([0.5244, 0.0010, 0.0009]))
(tensor([0.2833, 0.4188]), tensor([0.7096, 0.0014, 0.0014]))
(tensor([0.1750, 0.0769]), tensor([0.4080, 0.0009, 0.0007]))
(tensor([0.3167, 0.2735]), tensor([ 0.6003,  0.0012, -0.0009]))
(tensor([0.3667, 0.1880]), tensor([0.5454, 0.0007, 0.0016]))
(tensor([0.3333, 0.1795]), tensor([5.1974e-01, 2.1134e-04, 6.9689e-04]))
(tensor([0.4833, 0.2308]), tensor([ 0.6553, -0.0016,  0.0027]))
(tensor([0.2667, 0.2051]), tensor([0.5214, 0.0008, 0.0013]))
(tensor

(tensor([0.1917, 0.2564]), tensor([ 5.5128e-01, -3.0521e-04, -3.1260e-04]))
(tensor([0.1583, 0.2308]), tensor([ 0.5481, -0.0022, -0.0006]))
(tensor([0.2833, 0.0171]), tensor([4.0938e-01, 1.3882e-04, 2.4498e-04]))
(tensor([0.3500, 0.3590]), tensor([0.7439, 0.0016, 0.0015]))
(tensor([0.1833, 0.2137]), tensor([ 4.8474e-01, -5.7944e-05,  2.7416e-04]))
(tensor([0.0500, 0.1624]), tensor([4.0326e-01, 3.6092e-04, 3.5101e-04]))
(tensor([0.1500, 0.1709]), tensor([0.4529, 0.0008, 0.0005]))
(tensor([0.2167, 0.3675]), tensor([5.8358e-01, 2.0594e-04, 6.9338e-04]))
(tensor([0.0500, 0.2137]), tensor([4.2471e-01, 2.2695e-04, 5.8673e-04]))
(tensor([0.3083, 0.3077]), tensor([6.2413e-01, 5.9848e-04, 9.6687e-04]))
(tensor([0.3000, 0.1966]), tensor([5.2527e-01, 1.6406e-04, 1.0296e-03]))
(tensor([0.4833, 0.1282]), tensor([5.1741e-01, 4.2736e-04, 1.0401e-03]))
(tensor([0.1417, 0.0256]), tensor([3.9128e-01, 5.0118e-05, 2.6483e-04]))
(tensor([0.1000, 0.1026]), tensor([0.3916, 0.0006, 0.0008]))
(tensor([0.1417, 

(tensor([0.4333, 0.2564]), tensor([0.6704, 0.0008, 0.0009]))
(tensor([0.4333, 0.3419]), tensor([8.1335e-01, 1.6767e-03, 5.0062e-04]))
(tensor([0.4667, 0.1111]), tensor([ 0.5189, -0.0016,  0.0016]))
(tensor([0.1583, 0.3761]), tensor([ 5.5995e-01,  5.0820e-04, -9.6933e-05]))
(tensor([0.3667, 0.3846]), tensor([ 0.7922,  0.0016, -0.0013]))
(tensor([0.3250, 0.2222]), tensor([ 0.5456, -0.0022,  0.0018]))
(tensor([0.0250, 0.0256]), tensor([3.7536e-01, 1.7842e-04, 8.5618e-05]))
(tensor([0.4667, 0.3504]), tensor([ 8.5424e-01, -3.9604e-05,  2.1295e-03]))
(tensor([0.1500, 0.1197]), tensor([0.4227, 0.0010, 0.0012]))
(tensor([0.1083, 0.1368]), tensor([4.0503e-01, 3.3553e-04, 1.9484e-04]))
(tensor([0.2333, 0.2564]), tensor([ 5.5216e-01, -2.2806e-05,  2.8858e-04]))
(tensor([0.2083, 0.0171]), tensor([ 3.9602e-01, -1.2593e-04,  4.0971e-04]))
(tensor([0.2667, 0.3675]), tensor([0.6393, 0.0012, 0.0007]))
(tensor([0.3250, 0.4786]), tensor([0.8199, 0.0017, 0.0026]))
(tensor([0.2750, 0.1026]), tensor([ 4.485